### PR TITLE
Re-rendered the feedstock for conda-smithy "2.4.5"

### PR DESCRIPTION
**Pull request by dwnoble**
Re-rendered the feedstock for conda-smithy "2.4.5" in order to support Python 3.6

### CODE REVIEW

**Comment by sodre** [comment]
can flask-bcrypt be converted to a noarch package? That way we would not need to rerender again when 3.7 comes up.

**Comment by dwnoble** [comment]
I don't see why not. I updated the PR and converted flask-bcrypt to a noarch package.

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
@conda-forge-admin please rerender

**Comment by pmlandwehr** [comment]
LGTM! Thanks! Merging.

**Pull request merged**
